### PR TITLE
fix: `compile` type no longer requires explicit generic

### LINKED ISSUE #18: Improve `compile` declaration to avoid having to manually add `<typeof function>` as a generic parameters.
love the new compile api, super cool how thats able to be done with `Proxy`
its great to just be able to pass in a *clean* component, and get out a new compiled one that type wise is identical

however I ran into some [strange type issues](https://gist.github.com/ethanniser/c1451e34f87d000f1dc4862053390118) (errors in comment of gist)

This might be solved by explicitly passing a generic, but the dx is so much better when that isnt necessary

After messing around a bit I refactored the type for `compile` and ended up with this

```ts
type StringPropsOnly<P> = {
  [K in keyof P]: string;
};

declare function myCompiled<P extends StringPropsOnly<P>>(
  this: void,
  component: (props: P) => JSX.Element,
  strict?: boolean,
  separator?: string
): (props: P) => JSX.Element;
```

which [resolved all of the issues I had](https://gist.github.com/ethanniser/bcf3f2771cac90310561e7fdc881828e)

---

The existing type still supports passing a tuple or record of strings, which I am assuming is a remnant from the old API.

Curious to your thoughts on this, but I think we should drop support for that, and just rely on inference from the function

---

thanks!

### PR DESCRIPTION
**Pull request by ethanniser**
closes #18 

This PR:

 - **Modifies the type signature of `compile` to infer all types from the passed component, meaning explictly passing a generic (`compile<typeof Component>`) is no longer neccessary**
 - **drops support for the old api of passing an array or record of strings as the generic**
 - updates all usages of `compile` in `/test/compile.test.tex`, `/benchmark/suite.ts`, and `README.md` to align with the changes
 - removed 2 redundant tests

 - [x] all tests and tsc passing

### CODE REVIEW

**Comment by ethanniser** [comment]
sorry didnt even know what signed commits were before this, just set that up for the future though

File: index.d.ts [hunk 1]
```diff
@@ -132,32 +132,22 @@ declare namespace html {
...
+   * @returns {Function} the compiled template function
    * @this {void}
    */
-  export function compile<
-    P extends
-      | Record<string, any>
-      | string[]
-      | ((args: Record<string, string>) => JSX.Element) = {}
-  >(
+  export function compile<P extends StringPropsOnly<P>>(
```
Comment (arthurfiorette) [inline index.d.ts:141]: I think we could inline this here

```suggestion
  export function compile<P extends { [K in keyof P]: string | number | boolean }>(
```

File: index.d.ts [hunk 2]
```diff
@@ -132,32 +132,22 @@ declare namespace html {
...
-        string
-      >
-    ) => JSX.Element,
+    component: Component<P>,
     strict?: boolean,
     separator?: string
-  ): typeof factory
+  ): Component<P>
+
+  type StringPropsOnly<P> = {
```
Comment (arthurfiorette) [inline index.d.ts:148]:
```suggestion
```

**Review by arthurfiorette — CHANGES_REQUESTED** [review]

**Comment by ethanniser** [comment]
maybe worth adding a test that ts expects for when a component is passed with props that are not `string | number | boolean`

File: index.d.ts (hunk 1 above)
Comment (arthurfiorette) [reply index.d.ts]: I think I'm going back with allowing non string types, it could give the false perception that the real props are going there...

File: index.d.ts [hunk 3]
```diff
@@ -132,32 +132,22 @@ declare namespace html {
...
+   * @returns {Function} the compiled template function
    * @this {void}
    */
-  export function compile<
-    P extends
-      | Record<string, any>
-      | string[]
-      | ((args: Record<string, string>) => JSX.Element) = {}
-  >(
+  export function compile<P extends { [K in keyof P]: string | number | boolean }>(
```
Comment (arthurfiorette) [inline index.d.ts:141]:
```suggestion
  export function compile<P extends { [K in keyof P]: string }>(
```

**Review by arthurfiorette — CHANGES_REQUESTED** [review]

File: index.d.ts (hunk 3 above)
Comment (ethanniser) [reply index.d.ts:141]: I agree, I think its better to make people call `toString` and have it be more explicit that what's happening is just string concattination

File: index.d.ts (hunk 2 above)
Comment (arthurfiorette) [reply index.d.ts:148]: Can you remove this type? thnx

**Comment by arthurfiorette** [comment]
Was trying `.compile` in some of my personal projects and almost everywhere I used `PropsWithChildren` typescript would get mad with me, I'm also pushing with this PR a feature that correctly handles multiple children on compiled components.

**Review by arthurfiorette — APPROVED** [review]

**Comment by arthurfiorette** [comment]
Thanks!
